version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-1
    AWS_ACCOUNT_ID: 090123123123
  parameter-store:
    DOCKER_USER: /app/common/docker_hub/user
    DOCKER_TOKEN: /app/common/docker_hub/token

phases:
  install:
    commands:
  pre_build: # ビルド前処理
    commands:
      - echo Clean file...
      - rm -rf .git .gitignore README.md
      - echo Logging in to Amazon ECR...
      - pip install awscli --upgrade
      - aws --version
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
      - IMAGE_NAME_NGINX=internal-app-api-nginx-${ENVIRONMENT}
      - IMAGE_NAME_PHP_FPM=internal-app-api-php-fpm-${ENVIRONMENT}
      - IMAGE_NAME_FLUENTBIT=internal-app-api-fluentbit-${ENVIRONMENT}
      - REPOSITORY_URI_NGINX=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME_NGINX}
      - REPOSITORY_URI_PHP_FPM=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME_PHP_FPM}
      - REPOSITORY_URI_FLUENTBIT=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME_FLUENTBIT}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build: #ビルドテスト
    commands:
      - echo ${REPOSITORY_URI_FLUENTBIT}
      - echo ${ENVIRONMENT}
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${REPOSITORY_URI_NGINX}:latest --build-arg ENVIRONMENT=${ENVIRONMENT} -f ./ecs/environments/${ENVIRONMENT}/docker/nginx/Dockerfile .
      - docker build -t ${REPOSITORY_URI_PHP_FPM}:latest --build-arg ENVIRONMENT=${ENVIRONMENT} -f ./ecs/environments/${ENVIRONMENT}/docker/php-fpm/Dockerfile .
      - docker build -t ${REPOSITORY_URI_FLUENTBIT}:latest --build-arg ENVIRONMENT=${ENVIRONMENT} -f ./ecs/environments/${ENVIRONMENT}/docker/fluentbit/Dockerfile .
      - docker tag ${REPOSITORY_URI_NGINX}:latest ${REPOSITORY_URI_NGINX}:$IMAGE_TAG
      - docker tag ${REPOSITORY_URI_PHP_FPM}:latest ${REPOSITORY_URI_PHP_FPM}:$IMAGE_TAG
      - docker tag ${REPOSITORY_URI_FLUENTBIT}:latest ${REPOSITORY_URI_FLUENTBIT}:$IMAGE_TAG
  post_build: # ECRへのプッシュ
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      # latest運用はしない
      - docker push ${REPOSITORY_URI_NGINX}:$IMAGE_TAG
      - docker push ${REPOSITORY_URI_PHP_FPM}:$IMAGE_TAG
      - docker push ${REPOSITORY_URI_FLUENTBIT}:$IMAGE_TAG
      - echo Writing image definitions file...
      - echo ${ENVIRONMENT}
      - cat ./ecs/environments/${ENVIRONMENT}/task_definition_template.json | sed -e s@\<REPOSITORY_URI_NGINX\>@$REPOSITORY_URI_NGINX:$IMAGE_TAG@ -e s@\<REPOSITORY_URI_FLUENTBIT\>@$REPOSITORY_URI_FLUENTBIT:$IMAGE_TAG@ -e s@\<REPOSITORY_URI_PHP_FPM\>@$REPOSITORY_URI_PHP_FPM:$IMAGE_TAG@ -e s@\<ENVIRONMENT\>@$ENVIRONMENT@ -e s@SED_TARGET_AWS_ACCOUNT_ID@$AWS_ACCOUNT_ID@g -e s@SED_TARGET_ENVIRONMENT@$ENVIRONMENT@g -e s@SED_TARGET_AWS_REGION@$AWS_REGION@g > ./ecs/environments/${ENVIRONMENT}/task_definition.json
      - cat ./ecs/environments/${ENVIRONMENT}/task_definition.json
artifacts:
  files:
    - ./ecs/environments/${ENVIRONMENT}/task_definition.json
    - ./ecs/environments/${ENVIRONMENT}/appspec.yaml
  discard-paths: yes # 中間のパスを無視してartifacts.zipのみ出力できる
